[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.4",
    "python-telegram-bot==13.15",
    "flask>=3.1.1",
    "telegram>=0.0.1",
]
